# -*- coding: utf-8 -*-
"""amstrong.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hUb5hoDw1afsR5jD_Z8IQ-v9l1sYndW6
"""

def list_digits(num):
    s=str(num)
    L=list(s)
    return L

def check_Amstrong():
    num=int(input("Enter number"))
    L=list_digits(num)
    print(L)
    L1=[]
    #lambda function to find power 
    b=lambda x:x**3
    for i in L:
        i=int(i)
        L1.append(b(i))
    total=sum(L1)
    if total==num:
        print(num," is an Amstrong num")
    else:
        print(num," is not an Amstrong num")

check_Amstrong()

